# Generated by Django 4.1.5 on 2023-01-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcategory',
            old_name='name_category',
            new_name='name',
        ),
    ]
