# Generated by Django 4.1.5 on 2023-01-04 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_rename_name_category_postcategory_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='text',
        ),
    ]
