# Generated by Django 4.1.5 on 2023-01-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='authenticate',
            field=models.BooleanField(default=False),
        ),
    ]
