# Generated by Django 4.1.5 on 2023-01-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0011_rename_profile_authuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='like',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TNK', 'Танк'), ('HL', 'Хилл'), ('DD', 'ДД'), ('MRCH', 'Торговец'), ('GMSTR', 'Гилдмастер'), ('QGVR', 'Квестгивер'), ('BLKMTH', 'Кузнец'), ('TNR', 'Кожевник'), ('PTN', 'Зельевар'), ('MSTRSPL', 'Мастер заклинаний')], default='TNK', max_length=128, verbose_name='Тип'),
        ),
    ]
